// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7EvY4-Kb4nYmHUzTDqgDt63tNdysHVjA',
    appId: '1:37225278961:android:5532b85c7f2d3c27cde850',
    messagingSenderId: '37225278961',
    projectId: 'nutriseesmart-9930c',
    storageBucket: 'nutriseesmart-9930c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKQEeaG5c90uKLabuzbo7WpzrlKMw9S_4',
    appId: '1:37225278961:ios:823b12135b3d6065cde850',
    messagingSenderId: '37225278961',
    projectId: 'nutriseesmart-9930c',
    storageBucket: 'nutriseesmart-9930c.firebasestorage.app',
    iosBundleId: 'com.example.nutrsesmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7EvY4-Kb4nYmHUzTDqgDt63tNdysHVjA',
    appId: '1:37225278961:windows:5532b85c7f2d3c27cde850',
    messagingSenderId: '37225278961',
    projectId: 'nutriseesmart-9930c',
    storageBucket: 'nutriseesmart-9930c.firebasestorage.app',
  );
}
